# -*- coding: utf-8 -*-
"""water_potability_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uw-tPJ8QnKSCVWdBLxTIfZvdHEYnxOJq
"""

import pandas as pd

water_data = pd.read_csv('/content/data/water_potability.csv')

corr = water_data.corr()

corr

heat_map = corr.style.background_gradient(cmap='coolwarm')

heat_map

